### ISSUE TITLE
Great list

### ISSUE THREAD

**Issue by Gdewilde** [tollwerk/data-processing-agreements#31]
Thanks for compiling this list. Can I use it to seed our [GDPR Tracker](https://gdprtracker.io/)?

**Comment by jkphl** [comment]
@Gdewilde Thanks for your inquiry! As @sebastiangreger pointed out, [this project is public domain](https://github.com/tollwerk/data-processing-agreements/blob/master/LICENSE) — so yes, please go ahead!
